revert update from urllib 1.23 to 1.24
requests 2.19.1 has requirement urllib3<1.24,>=1.21.1, but you have urllib3 1.24.
ERROR: InvocationError for command '/home/travis/build/mozilla-releng/mozilla-version/.tox/docs-localbuild/bin/pip check' (exited with code 1)