Scheduled weekly dependency update for week 41 (#39)
* Update certifi from 2018.8.24 to 2018.10.15

* Update certifi from 2018.8.24 to 2018.10.15

* Update urllib3 from 1.23 to 1.24

* Update urllib3 from 1.23 to 1.24

* Update m2r from 0.2.0 to 0.2.1

* Update mistune from 0.8.3 to 0.8.4

* Update pluggy from 0.7.1 to 0.8.0

* Update py from 1.6.0 to 1.7.0

* Update pydocstyle from 2.1.1 to 3.0.0

* Update pytest from 3.8.2 to 3.9.1

* revert update from urllib 1.23 to 1.24

requests 2.19.1 has requirement urllib3<1.24,>=1.21.1, but you have urllib3 1.24.
ERROR: InvocationError for command '/home/travis/build/mozilla-releng/mozilla-version/.tox/docs-localbuild/bin/pip check' (exited with code 1)

* revert urllib3 from 1.24 to 1.23